### ISSUE TITLE
Small bug

### ISSUE THREAD

**Issue by xbarretox** [EduMIPS64/edumips64#1048]
```java
java.lang.StringIndexOutOfBoundsException: Index 5 out of bounds for length 5
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.lang.String.checkIndex(String.java:4832)
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:46)
	at java.base/java.lang.String.charAt(String.java:1555)
	at org.edumips64.core.parser.Parser.doParsing(Parser.java:751)
	at org.edumips64.core.parser.Parser.parse(Parser.java:132)
	at org.edumips64.Main.openFile(Main.java:521)
	at org.edumips64.Main.lambda$createMenuBar$5(Main.java:787)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1029)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1073)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6621)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
	at java.desktop/java.awt.Component.processEvent(Component.java:6386)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
## System information
 * Version: 1.3.0
 * Build date: 2023-10-17T18:28:27.407233900
 * Git revision: master@f7753dc
 * JRE version: 21.0.3
 * OS: Mac OS X

## Code of the assembly file in execution
<details><summary>Click to expand</summary>

```assembly
.data
a: .word 5 ; Valor inicial para a
b: .word 3 ; Valor inicial para b
c: .word 0 ; c inicializado como 0 (sera usado para armazenar resultados)
.text
.globl main
main:
lw $t0,a ; Carrega o valor de a em $t0
lw $t1,b ; Carrega o valor de b em $t1
add $t2,$t0,$t1 ; c = a + b
sw $t2,c ; Armazena o resultado de c na memoria
sub $t2,$t0,$t1 ; c = a - b
sw $t2,c ; Armazena o resultado de c na memoria
mul $t2,$t0,$t1 ; c = a * b
sw $t2,c ; Armazena o resultado de c na memoria
div $t0,$t1 ; Divisao a / b
mflo $t2 ; Move o resultado da divisao para c
sw $t2,c ; Armazena o resultado de c na memoria
div $t0,$t1 ; Prepara novamente a / b para calcular o modulo
mfhi $t2 ; Move o resto da divisao para c
sw $t2,c ; Armazena o resultado de c na memoria
jr $ra ; Retorna do main

```
</details>

**Comment by lupino3** [comment]
Hi @xbarretox, and thanks for the bug report! I can confirm this happens on Windows as well, I will investigate as soon as possible. Thank you!

**Comment by lupino3** [comment]
Thanks for reporting the bug and allowing us to fix it.
If you compile and run the latest version, you should now see a clean list of errors that will allow you to fix them and get your program to run.

Please don't hesitate to reopen the issue if you feel it hasn't been addressed or reach out for further help. Thanks!
